# Formations et Cours en Bioinformatique

**Ghislain BIDAUT**\
*Ingénieur de Recherche — Aix-Marseille Université*

------------------------------------------------------------------------

## Présentation

Bienvenue sur cette page qui regroupe les supports utilisés dans mes enseignements de **bioinformatique**.

::: callout-note
La majorité des documents proposés sont des *slides* au format **PDF**, volontairement synthétiques, conçus pour accompagner le cours et en souligner les points essentiels.
:::

Les **travaux dirigés (TDs)** sont quant à eux plus détaillés et permettent un apprentissage progressif, pas à pas.

Les **données** sont fournies sous forme d’objets **R** (`.RData`), à charger directement dans le logiciel **RStudio**.

------------------------------------------------------------------------

## Supports de cours magistraux

| Titre | Niveau | Supports |
|------------------------|------------------------|------------------------|
| **Analyse bioinformatique des données moléculaires à haut débit en Oncologie** | M1 | [Support](./cours/Cours-Master-M1-Genomique-Variants_RNA_Seq.html) |
| **Data classification and application in genomics and transcriptomics** | M2 | [Support](./cours/M2-Bio-Sante-IA-Biomarkers-Classif-Genomics-Data.html) |
| **Analyse bioinformatique appliquée à l’Oncologie: Analyses RNA-seq et Single Cell RNA-seq** | M2 | [Support](./cours/Cours-M2_Technologies-de-la-Santé_RNA-Seq_Single-Cell.html) |
| **Introduction à la bioinformatique en Oncologie** | M2 | [Support](./cours/ours-Intro-Bioinfo-Onco-M2-Biologie-Santé-Tronc-Commun-Genomique.html) |
| **Biological networks and human diseases** | M2 | [Support](./cours/M2-Biologie-Santé-Genomique-Réseaux-Biologiques-et-Maladies-Humaines.pdf) |

## Travaux Dirigés

| Titre | Niveau | Supports |
|------------------------|------------------------|------------------------|
| **Etude d'un pipeline d'appel de variants constitutionnels** | M2 | [Support](./cours/TD_Master_Bioinfo_DNA-seq_appel_de_variants.html) |

## Formations

| Titre | Niveau | Supports |
|------------------------|------------------------|------------------------|
| **Traiter ses données NGS (DNA-seq et RNA-seq) sous Linux** | Formation permanente | [Site web](https://reposgb.github.io/formation_ngs_linux/) |
| **Analyser ses données de séquençage NGS RNA-seq sous R/Bioconductor** | Formation permanente | [Site web](https://reposgb.github.io/formation_rnaseq_r/) |
| **Traiter ses données NGS (Single cell RNA-seq, RNA-seq bulk et DNA-seq) sous nf-core sur cluster de calcul** | Formation Permanente | [Site web]() |
| **Prise en main des analyses de données scRNA-Seq sous R+RStudio** | Formation permanente | [Site web]() |

## Licence

{{< include _includes/licence.qmd >}}
